#! /usr/bin/env python3

import http.server
import socketserver
import os
import pathlib
import sys
import MarkdocHttpRequestHandler
import wx
import webbrowser

my_dir = pathlib.Path(os.path.realpath(__file__)).parent.absolute()
print(my_dir)

def get_path(wildcard):
    app = wx.App(None)
    style = wx.FD_OPEN | wx.FD_FILE_MUST_EXIST
    dialog = wx.FileDialog(None, 'Open', wildcard=wildcard, style=style)
    if dialog.ShowModal() == wx.ID_OK:
        path = dialog.GetPath()
    else:
        path = None
    dialog.Destroy()
    return path

md_file = ''
md_dir = ''

if (len(sys.argv) != 2):
    md_file = os.path.abspath(get_path('*.md'))
else:
    md_file = os.path.abspath(sys.argv[1])
md_dir = os.path.dirname(md_file)

os.chdir(my_dir)

MarkdocHttpRequestHandler.md_file = md_file
MarkdocHttpRequestHandler.md_dir = md_dir

socketserver.TCPServer.allow_reuse_address = True

Handler = MarkdocHttpRequestHandler.MarkdocRequestHandler

PORT = 8080

while True:
    try:
        with socketserver.TCPServer(("",PORT),Handler) as httpd:
            print("serving on localhost:%i" % PORT)
            webbrowser.open("http://localhost:%d" % PORT)
            try:
                httpd.serve_forever()
            except:
                print("Closing the server.")
                httpd.server_close()
                raise
    except OSError as e:
        PORT += 1
